In [1]:
import numpy as np

In [3]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [4]:
print (v1)
print (v2)

[1 2 3]
[4 5 6]


In [5]:
v_add = v1 + v2
v_sub = v1 - v2

In [6]:
print (v_add)
print (v_sub)

[5 7 9]
[-3 -3 -3]


In [7]:
scalar = 2
v_scaled = scalar * v1

In [8]:
print (v_scaled)

[2 4 6]


In [9]:
dot_product = np.dot(v1, v2)

In [10]:
print (dot_product)

32


In [11]:
magnitude_v1 = np.linalg.norm(v1)

In [12]:
print (magnitude_v1)

3.7416573867739413


In [13]:
C = np.array ([1, 2, 3], [4, 5, 6])
matrix_add = A + C
matrix_add = A - C

print ("A+C=\n", matrix_add)
print ("A-C=\n", matrix_sub)

TypeError: data type not understood

In [14]:
matrix_mul = np.dot(A, B)

print (matrix_mul)

NameError: name 'A' is not defined

In [15]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix A:\n", A)

Matrix A:
 [[1 2 3]
 [4 5 6]]


In [16]:
B = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
print("Matrix B:\n", B)


Matrix B:
 [[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [17]:
matrix_mul = np.dot(A, B)

print (matrix_mul)

[[ 66  72  78]
 [156 171 186]]


In [18]:
transpose_A = A.T
print (transpose_A)

[[1 4]
 [2 5]
 [3 6]]


In [19]:
A = np.array ([[2,3,0], [4,-1,0], [1,1,0]])
b = np.array ([5,3,2])

print (A)
print (b)

x = np.linalg.solve(A,b)
print ("solution (x, y): ",x)

[[ 2  3  0]
 [ 4 -1  0]
 [ 1  1  0]]
[5 3 2]


LinAlgError: Singular matrix

In [21]:
A = np.array ([[2, 1], [1, 2]])
e_value, e_vectors = np.linalg.eig(A)

In [22]:
print ("eigenvalue:", e_value)
print ("eigenvector:", e_vector)

eigenvalue: [3. 1.]


NameError: name 'e_vector' is not defined

In [ ]:
A = np.array ([[4, 7], [2, 6]])