In [3]:
import numpy as np
import time

def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    start = time.perf_counter()
    for k in range(max_iterations):
        x_old = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x[i] = (b[i] - s1 - s2) / A[i][i] 
        
        if np.isinf(x).any():
            return x, k + 1, time.perf_counter() - start
            
        if np.linalg.norm(x_old - x, ord=np.inf) < tol:
            return x, k + 1, time.perf_counter() - start
    return x, max_iterations, time.perf_counter() - start

def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    start = time.perf_counter()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        
        if np.isinf(x_new).any():
            return x_new, k + 1, time.perf_counter() - start
            
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k + 1, time.perf_counter() - start
        x = x_new
    return x, max_iterations, time.perf_counter() - start

A = np.array([[0.582745, 0.48, 0.10, 0., 0. ], 
 [0.48, 1.044129, 0.46, 0.10, 0.],
 [0.10, 0.46, 1.10431 , 0.44, 0.10],
 [0., 0.10, 0.44, 0.963889, 0.42],
 [0., 0., 0.10, 0.42, 0.522565]], dtype=float)
b = np.array([1.162745, 2.084129, 2.20431 , 1.923889, 1.042565], dtype=float)

x0 = np.zeros(5)
tol = 1e-6
max_limit = 100

sol_jac, iter_jac, time_jac = jacobi(A, b, x0, tol, max_limit)
sol_gs, iter_gs, time_gs = gauss_seidel(A, b, x0, tol, max_limit)

if iter_jac == 100:
    print(f"Jacobi: Does not converge")
else:
    print(f"Jacobi took {iter_jac} steps and {time_jac:.6f} seconds") ## Runs the Jacobi equation

if iter_gs == 100:
    print(f"Gauss-Seidel: Does not converge")
else:
    print(f"Gauss-Seidel took {iter_gs} steps and {time_gs:.6f} seconds") ## Runs the Gauss-Seidel equation

Jacobi: Does not converge
Gauss-Seidel took 21 steps and 0.001312 seconds


In [4]:
import numpy as np
import time

def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    start = time.perf_counter()
    for k in range(max_iterations):
        x_old = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x[i] = (b[i] - s1 - s2) / A[i][i] 
        
        if np.isinf(x).any():
            return x, k + 1, time.perf_counter() - start
            
        if np.linalg.norm(x_old - x, ord=np.inf) < tol:
            return x, k + 1, time.perf_counter() - start
    return x, max_iterations, time.perf_counter() - start

def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    start = time.perf_counter()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        
        if np.isinf(x_new).any():
            return x_new, k + 1, time.perf_counter() - start
            
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k + 1, time.perf_counter() - start
        x = x_new
    return x, max_iterations, time.perf_counter() - start

A = np.array([[1, 1], [1, 1.0001]])
b = np.array([1, 1])

x0 = np.zeros(5)
tol = 1e-6
max_limit = 100

sol_jac, iter_jac, time_jac = jacobi(A, b, x0, tol, max_limit)
sol_gs, iter_gs, time_gs = gauss_seidel(A, b, x0, tol, max_limit)

if iter_jac == 100:
    print(f"Jacobi: Does not converge")
else:
    print(f"Jacobi took {iter_jac} steps and {time_jac:.6f} seconds") ## Runs the Jacobi equation

if iter_gs == 100:
    print(f"Gauss-Seidel: Does not converge")
else:
    print(f"Gauss-Seidel took {iter_gs} steps and {time_gs:.6f} seconds") ## Runs the Gauss-Seidel equation

Jacobi: Does not converge
Gauss-Seidel took 2 steps and 0.000227 seconds


In [12]:
import numpy as np
import time

def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    start = time.perf_counter()
    for k in range(max_iterations):
        x_old = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x[i] = (b[i] - s1 - s2) / A[i][i] 
        
        if np.isinf(x).any():
            return x, k + 1, time.perf_counter() - start
            
        if np.linalg.norm(x_old - x, ord=np.inf) < tol:
            return x, k + 1, time.perf_counter() - start
    return x, max_iterations, time.perf_counter() - start

def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    start = time.perf_counter()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        
        if np.isinf(x_new).any():
            return x_new, k + 1, time.perf_counter() - start
            
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k + 1, time.perf_counter() - start
        x = x_new
    return x, max_iterations, time.perf_counter() - start

A = np.array([[1, 1], [1, 1.0001]])
b = np.array([1, 1.0001])

x0 = np.zeros(5)
tol = 1e-6
max_limit = 100

sol_jac, iter_jac, time_jac = jacobi(A, b, x0, tol, max_limit)
sol_gs, iter_gs, time_gs = gauss_seidel(A, b, x0, tol, max_limit)

if iter_jac == 100:
    print(f"Jacobi: Does not converge")
else:
    print(f"Jacobi took {iter_jac} steps and {time_jac:.6f} seconds") ## Runs the Jacobi equation

if iter_gs == 100:
    print(f"Gauss-Seidel: Does not converge")
else:
    print(f"Gauss-Seidel took {iter_gs} steps and {time_gs:.6f} seconds") ## Runs the Gauss-Seidel equation

Jacobi: Does not converge
Gauss-Seidel: Does not converge


In [6]:
import numpy as np
A = np.array([[2,1],[1,1]])
B = np.array([[2,4],[1,2]])
print (np.linalg.det(A))
print (np.linalg.det(B))

1.0
0.0


In [8]:
Ainv = np.linalg.inv(A)
#Binv = np.linalg.inv(B)

print (Ainv)
#print (Binv)

[[ 1. -1.]
 [-1.  2.]]


In [10]:
print (A)
print (f"{A}")
kappa = np.linalg.cond(A, 2)
print (kappa)

[[2 1]
 [1 1]]
[[2 1]
 [1 1]]
6.854101966249688


In [11]:
import numpy as np
import time

def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    start = time.perf_counter()
    for k in range(max_iterations):
        x_old = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x[i] = (b[i] - s1 - s2) / A[i][i] 
        
        if np.isinf(x).any():
            return x, k + 1, time.perf_counter() - start
            
        if np.linalg.norm(x_old - x, ord=np.inf) < tol:
            return x, k + 1, time.perf_counter() - start
    return x, max_iterations, time.perf_counter() - start

def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    start = time.perf_counter()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        
        if np.isinf(x_new).any():
            return x_new, k + 1, time.perf_counter() - start
            
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k + 1, time.perf_counter() - start
        x = x_new
    return x, max_iterations, time.perf_counter() - start

A = np.array([[0.582745, 0.48, 0.10, 0., 0. ], 
 [0.48, 1.044129, 0.46, 0.10, 0.],
 [0.10, 0.46, 1.10431 , 0.44, 0.10],
 [0., 0.10, 0.44, 0.963889, 0.42],
 [0., 0., 0.10, 0.42, 0.522565]], dtype=float)
b = np.array([1.162745, 2.084129, 2.20431 , 1.923889, 1.042565], dtype=float)

x0 = np.zeros(5)
tol = 1e-6
max_limit = 100

sol_jac, iter_jac, time_jac = jacobi(A, b, x0, tol, max_limit)
sol_gs, iter_gs, time_gs = gauss_seidel(A, b, x0, tol, max_limit)

if iter_jac == 100:
    print(f"Jacobi: Does not converge")
else:
    print(f"Jacobi took {iter_jac} steps and {time_jac:.6f} seconds") ## Runs the Jacobi equation

if iter_gs == 100:
    print(f"Gauss-Seidel: Does not converge")
else:
    print(f"Gauss-Seidel took {iter_gs} steps and {time_gs:.6f} seconds") ## Runs the Gauss-Seidel equation
    
print (A)
print (f"{A}")
kappa = np.linalg.cond(A, 2)
print (kappa)

Jacobi: Does not converge
Gauss-Seidel took 21 steps and 0.001521 seconds
[[0.582745 0.48     0.1      0.       0.      ]
 [0.48     1.044129 0.46     0.1      0.      ]
 [0.1      0.46     1.10431  0.44     0.1     ]
 [0.       0.1      0.44     0.963889 0.42    ]
 [0.       0.       0.1      0.42     0.522565]]
[[0.582745 0.48     0.1      0.       0.      ]
 [0.48     1.044129 0.46     0.1      0.      ]
 [0.1      0.46     1.10431  0.44     0.1     ]
 [0.       0.1      0.44     0.963889 0.42    ]
 [0.       0.       0.1      0.42     0.522565]]
8.067443024472189


In [18]:
import numpy as np
def is_diagonally_dominant(A):
    n = len(A)

    for i in range(n):
        diagonal = abs(A[i][i])
        row_sum = sum(abs(A[i][j]) for j in range(n) if j != i)

        if diagonal < row_sum:
            return False

    return True

A = np.array([[0.582745, 0.48, 0.10, 0., 0. ], 
 [0.48, 1.044129, 0.46, 0.10, 0.],
 [0.10, 0.46, 1.10431 , 0.44, 0.10],
 [0., 0.10, 0.44, 0.963889, 0.42],
 [0., 0., 0.10, 0.42, 0.522565]])

for row in A:
    print(row)

print("Is the matrix diagonally dominant?", is_diagonally_dominant(A))

[0.582745 0.48     0.1      0.       0.      ]
[0.48     1.044129 0.46     0.1      0.      ]
[0.1     0.46    1.10431 0.44    0.1    ]
[0.       0.1      0.44     0.963889 0.42    ]
[0.       0.       0.1      0.42     0.522565]
Is the matrix diagonally dominant? True
