In [43]:
import numpy as np
from scipy.linalg import lu

In [ ]:
def gaussian_elimination(A, b):
    n = len(b)
    
    for i in range(n):
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]

        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] = [A[j][k] - ratio * A[i][k] for k in range(n)]
            b[j] -= ratio * b[i]
    
    x = [0] * n  ##Backwards sub
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]
    return x

In [58]:
def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)
    U = np.array(A, dtype=float)

    for i in range(n):
        for j in range(i+1, n):
            if U[i, i] == 0:
                raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")
                factor = U[j, i] / U[i, i]
                
            L[j, i] = factor
        
            for k in range(i, n):
                U[j, k] -= factor * U[i, k]
    
    return L, U

A = np.array([[2, 3, 1],[4, 7, -1],[-2, 1, 2]])

# Perform LU Decomposition
P, L, U = lu(A)
print("Matrix A:\n", A)
print("Permutation Matrix P:\n", P)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)
print(np.matmul(L, U))
print(P@L@U)

Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Permutation Matrix P:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Lower Triangular Matrix L:
 [[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.5        -0.11111111  1.        ]]
Upper Triangular Matrix U:
 [[ 4.          7.         -1.        ]
 [ 0.          4.5         1.5       ]
 [ 0.          0.          1.66666667]]
[[ 4.  7. -1.]
 [-2.  1.  2.]
 [ 2.  3.  1.]]
[[ 2.  3.  1.]
 [ 4.  7. -1.]
 [-2.  1.  2.]]
